---
abstract: 'test sugar for methods'
author:
  - 'Caleb Cushing <xenoterracide@gmail.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::Deep: 0
  Test::More: 0.88
  Test::Tester: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Method
no_index:
  file:
    - perlcritic.rc
requires:
  Carp: 0
  Exporter: 0
  Scalar::Util: 0
  Test::Builder: 0
  Test::Deep::NoTest: 0
  Test::More: 0
  parent: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/xenoterracide/test-method/issues
  homepage: https://metacpan.org/dist/Test-Method
  repository: git://github.com/xenoterracide/test-method.git
version: 0.001000
